### PR TITLE
feat: add support for github deployments

### LINKED ISSUE #24: Support GitHub Deployments
Add a status list/map that allows deployments to be created/updated from a git repo object.
```
type Deployment stuct {
Name, Revision, Created,Completed,Status, Reason,Description string
}
```

### PR DESCRIPTION
**Pull request by Kaitou786**
closes #24

Signed-off-by: Tarun Khandelwal <tarun@flanksource.com>

### Description

Adding support for git deployments

### Dependencies

none

### Breaking Change

- [ ] Yes
- [x] No

### Testing Notes

**What I did:**
Added support to create and modify a GH deployment based on the `Ref` of the deployment. Once a GitDeployment Object is created it will create GH deployment/ after the Gh deployment is successfully created you will be able to see the status of your k8s object. This is a bidirectional implementation, so if you have some Deployments on your repositories it'll create a k8s object for those(if not already exists) if they exist it'll modify them based on the GH deployment. 

**How you can replicate my testing:**
1. create a gitrepository object which has some git deployments
2. Create GitDeployment Object with labels `"git.flanksource.com/repository": <GitRepository-Object-name>,`
3. Check the GH deployment being created on the  https://api.github.com/repos/<your-namespace>/<your_repo>/deployments
3. edit the gitdeployments ref field and verify the change on the GH deployment as well as k8s object. Until they are in sync the status.ref and spec.ref will point to diff values.
4. If some GH deployment already exist than the k8s object for them will be created.

### **Links**
See all the git deployments on the repo using:
```
curl  -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/<your-namespace>/<your_repo>/deployments
```

### CODE REVIEW

**Comment by moshloop** [comment]
Can we do a test (manual is ok) for this:

Create a new gitdeployment object and check deployment is created on github

**Comment by Kaitou786** [comment]
Currently it won't be created. I could not figure out how to proceed with that. Right now the implementation is when creating gitrepo object if deployment exists on the repo they'll be created as the k8s objects. When you update that k8s object (ref) field it'll delete the old Gitdeployment on the repo as well as the k8s object and create a new Gitdeployment with the new ref. Which in the next reconciliation will create a new k8s object. If we need to create a Gitdeployment from a k8s object I might need to rethink the current implementation

**Comment by moshloop** [comment]
Creating the git deployment from the k8 object is the primary objective to allow tools like Flux/ArgoCD to oush the results of deployments back to Github

**Comment by Kaitou786** [comment]
> Creating the git deployment from the k8 object is the primary objective to allow tools like Flux/ArgoCD to oush the results of deployments back to Github

Now it can be done :)

**Pull request merged**
